apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: console-sa-bind
subjects:
- kind: ServiceAccount
  namespace: default
  name: console-sa
roleRef:
  kind: ClusterRole
  name: cluster-read
  apiGroup: rbac.authorization.k8s.io
